version: '3.7'

services:
  sweep_to_omnibus_job:
    image: sweep_to_omnibus_job_image
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/src
    ports:
      - "8888:8000"
    networks:
      - base-network


networks:
  base-network:
    external: true
